BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "items" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL,
	"description"	TEXT NOT NULL,
	"price"	REAL NOT NULL,
	"stocks"	INTEGER NOT NULL,
	"categories"	TEXT NOT NULL,
	"colors"	TEXT NOT NULL DEFAULT '[]',
	"materialTypes"	TEXT NOT NULL DEFAULT '[]',
	"materials"	TEXT NOT NULL DEFAULT '[]',
	"width"	INTEGER NOT NULL DEFAULT 0,
	"depth"	INTEGER NOT NULL DEFAULT 0,
	"height"	INTEGER NOT NULL DEFAULT 0,
	"mainImage"	TEXT NOT NULL,
	"reviews"	TEXT NOT NULL DEFAULT '[]',
	"rating"	REAL,
	"reviewCount"	INTEGER NOT NULL DEFAULT 0,
	"sales"	INTEGER NOT NULL DEFAULT 0,
	"date"	TEXT NOT NULL,
	"brand"	TEXT NOT NULL DEFAULT 'ACME Furniture',
	"featured"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "users" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL,
	"username"	TEXT NOT NULL UNIQUE,
	"email"	TEXT NOT NULL,
	"password"	TEXT NOT NULL,
	"DOB"	TEXT NOT NULL,
	"points"	INTEGER NOT NULL DEFAULT 0,
	"rank"	INTEGER NOT NULL DEFAULT 1,
	"orders"	TEXT NOT NULL DEFAULT '[]',
	"cart"	TEXT NOT NULL DEFAULT '[]',
	"profile"	TEXT NOT NULL DEFAULT '\public\img\user-icons\unknown-user-icon.png',
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "items" VALUES (1,'Acacia Wood Chair','A nice wooden chair made from acacia.',14.99,11,'chair','["Brown"]','["Wood"]','["Acacia"]',12,12,24,'\\img\\products\\acacia-wood-chair.png','[{"rating": 5, "content": "Works Great! NO Problems Had", "userId": 9999}]',5.0,1,1,'2024-12-08','ACME Furniture',0);
INSERT INTO "items" VALUES (2,'Aqua Fabric Bean Bag','A beutiful aqua colored bean bag to relax away the day in.',25.99,6,'bean bag','["Other"]','["Fabric"]','["Cloth"]',36,36,30,'\\img\\products\\aqua-fabric-bean-bag.png','[{"rating": 5, "content": "Works Great! NO Problems Had", "userId": 9999}, {"rating": 3, "content": "Not my Favorite, a bit wobbly", "userId": 9985}, {"rating": 4, "content": "Its decent", "userId": 9989}]',4.0,3,3,'2022-02-08','Homeware Inc.',0);
INSERT INTO "items" VALUES (3,'Birch Wood Chair','A sleek birch wood chair.',15.99,4,'chair','["Beige"]','["Wood"]','["Birch"]',12,12,22,'\\img\\products\\birch-wood-chair.png','[{"rating": 5, "content": "Works Great! NO Problems Had", "userId": 9999}, {"rating": 3, "content": "Not my Favorite, a bit wobbly", "userId": 9985}, {"rating": 4, "content": "Its decent", "userId": 9989}]',4.0,3,4,'2023-01-01','ACME Furniture',0);
INSERT INTO "items" VALUES (4,'Birch Wood Table','A sturdy birch wood table for a family of four.',29.99,8,'table','["Beige"]','["Wood"]','["Birch"]',48,24,28,'\\img\\products\\birch-wood-table.png','[{"rating": 5, "content": "Works Great! NO Problems Had", "userId": 9999}, {"rating": 4, "content": "Its decent", "userId": 9989}]',4.5,2,9,'2024-12-01','ACME Furniture',0);
INSERT INTO "items" VALUES (5,'Black Leather Chair','A modern leather chair for your living room.',34.99,7,'chair','["Black"]','["Fabric", "Metal"]','["Leather", "Aluminum"]',40,40,44,'\\img\\products\\black-leather-chair.png','[{"rating": 5, "content": "Works Great! NO Problems Had", "userId": 9999}]',5.0,1,2,'2019-01-09','ACME Furniture',0);
INSERT INTO "items" VALUES (6,'Black Plastic Desk Chair','An ergonomic chair for perfect productivity.',49.99,4,'chair','["Black"]','["Plastic", "Fabric"]','["Polypropylene", "Leather"]',24,24,48,'\\img\\products\\black-plastic-desk-chair.png','[{"rating": 5, "content": "Works Great! NO Problems Had", "userId": 9999}]',5.0,1,20,'2021-03-05','Office Pal',0);
INSERT INTO "items" VALUES (7,'Black Leather Sofa','A large sofa that will be a greate addition to the living room.',79.99,3,'sofa','["Black"]','["Fabric", "Wood"]','["Leather", "Oak"]',54,36,40,'\\img\\products\\black-leather-sofa.png','[{"rating": 1, "content": "AWFUL!!!", "userId": 9966}, {"rating": 4, "content": "Its decent", "userId": 9989}]',2.5,2,5,'2019-11-13','ACME Furniture',0);
INSERT INTO "items" VALUES (8,'Blue King Size Bed','A luxurious blue king sized bed with silky soft velvet.',99.99,3,'bed','["Blue"]','["Fabric", "Wood"]','["Cloth", "Velvet", "Birch"]',76,80,48,'\\img\\products\\blue-king-sized-bed.png','[{"rating": 1, "content": "AWFUL!!!", "userId": 9966}, {"rating": 4, "content": "Its decent", "userId": 9989}]',2.5,2,4,'2020-12-01','ACME Furniture',0);
INSERT INTO "items" VALUES (9,'Blue Plastic Chair','A cheap blue plastic chair. Good for parties and classrooms.',12.99,14,'chair','["Blue"]','["Plastic"]','["Polyethylene"]',12,12,24,'\\img\\products\\blue-plastic-chair.png','[]',NULL,0,0,'2020-06-24','ACME Furniture',0);
INSERT INTO "items" VALUES (10,'Blue Plastic Desk Chair','A nice ergonomic desk chair for optimal focus.',31.99,16,'chair','["Blue"]','["Plastic", "Fabric"]','["Polypropylene", "Leather"]',24,24,48,'\\img\\products\\blue-plastic-desk-chair.png','[{"rating": 5, "content": "Works Great! NO Problems Had", "userId": 9999}, {"rating": 4, "content": "Its decent", "userId": 9989}]',4.5,2,31,'2024-01-12','Office Pal',0);
INSERT INTO "items" VALUES (11,'Blue Velvet Sofa','A goreous sofa for the fanciest of livng rooms.',82.99,5,'sofa','["Blue", "Black"]','["Fabric", "Metal"]','["Velvet", "Brass"]',78,36,36,'\\img\\products\\blue-velvet-sofa.png','[{"rating": 5, "content": "Works Great! NO Problems Had", "userId": 9999}, {"rating": 4, "content": "Its decent", "userId": 9989}]',4.5,2,3,'2019-01-02','ACME Furniture',0);
INSERT INTO "items" VALUES (12,'Brown Leather Chair','A comfy leather chair.',32.99,14,'chair','["Brown"]','["Fabric", "Wood"]','["Leather", "Mahogany"]',40,36,40,'\\img\\products\\brown-leather-chair.png','[{"rating": 5, "content": "Works Great! NO Problems Had", "userId": 9999}, {"rating": 4, "content": "Its decent", "userId": 9989}]',4.5,2,46,'2021-02-02','ACME Furniture',0);
INSERT INTO "items" VALUES (13,'Brown Leather Sofa','A large sofa that will be a lovely addition to your living room.',80.99,12,'sofa','["Brown"]','["Fabric", "Wood"]','["Leather", "Spruce"]',78,36,40,'\\img\\products\\brown-leather-sofa.png','[]',NULL,0,0,'2020-05-06','ACME Furniture',0);
INSERT INTO "items" VALUES (14,'Brown Wooden Desk','A nice wooden desk for peaceful studying.',45.99,23,'desk','["Brown"]','["Wood"]','["Spruce"]',48,24,28,'\\img\\products\\brown-wooden-desk.png','[{"rating": 5, "content": "Works Great! NO Problems Had", "userId": 9999}, {"rating": 3, "content": "Not my Favorite, a bit wobbly", "userId": 9985}]',4.0,2,7,'2024-07-09','Office Pal',0);
INSERT INTO "items" VALUES (15,'Concrete Table','A rugged concrete dinner table.',199.99,8,'table','["Gray"]','["Stone"]','["Concrete"]',48,24,24,'\\img\\products\\concrete-table.png','[{"rating": 5, "content": "Works Great! NO Problems Had", "userId": 9999}]',5.0,1,20,'2024-02-10','Homeware Inc.',0);
INSERT INTO "items" VALUES (16,'Concrete Table With Metal Legs','A rugged concrete dinner table with dark metal legs.',195.99,7,'table','["Gray"]','["Stone", "Metal"]','["Concrete", "Steel"]',48,24,20,'\\img\\products\\concrete-with-metal-legs-table.png','[]',NULL,0,20,'2020-07-11','Homeware Inc.',0);
INSERT INTO "items" VALUES (17,'Glass And Metal Circular Table','A round glass table with a shiny metal rim and base.',70.99,13,'table','["Clear", "Shiny"]','["Other", "Metal"]','["Glass", "Aluminum"]',36,36,28,'\\img\\products\\glass-and-metal-circular-table.png','[{"rating": 3, "content": "Not my Favorite, a bit wobbly", "userId": 9985}]',3.0,1,1,'2024-01-19','ACME Furniture',0);
INSERT INTO "items" VALUES (18,'Glass And Metal Table','A gorgeous glass dining table for those with modern sensibilities.',99.99,11,'table','["Clear", "Shiny"]','["Other", "Metal"]','["Glass", "Aluminum"]',48,24,24,'\\img\\products\\glass-and-metal-table.png','[]',NULL,0,0,'2024-03-18','ACME Furniture',0);
INSERT INTO "items" VALUES (19,'Granite Table with Metal Legs','A granite dining table for a family of four.',109.99,4,'table','["Black", "White", "Shiny"]','["Stone", "Metal"]','["Granite", "Steel"]',48,24,24,'\\img\\products\\granite-and-metal-legged-table.png','[]',NULL,0,17,'2024-05-13','Homeware Inc.',0);
INSERT INTO "items" VALUES (20,'Green Leather Chair','A nice green leather chair for anyone''s living room.',39.99,7,'chair','["Green"]','["Fabric", "Wood"]','["Leather", "Oak"]',36,36,40,'\\img\\products\\green-leather-chair.png','[{"rating": 1, "content": "AWFUL!!!", "userId": 9966}, {"rating": 4, "content": "Its decent", "userId": 9989}]',2.5,2,18,'2025-03-23','ACME Furniture',0);
INSERT INTO "items" VALUES (21,'Green Plastic Chair','A cheap green plastic chair. Good for parties and classrooms.',13.99,10,'chair','["Green"]','["Plastic"]','["Polyethylene"]',12,12,24,'\\img\\products\\green-plastic-chair.png','[]',NULL,0,0,'2025-08-24','ACME Furniture',0);
INSERT INTO "items" VALUES (22,'Green Velvet Sofa','A lovely velvet sofa for a fancy living room.',75.99,6,'sofa','["Green"]','["Fabric", "Wood"]','["Velvet", "Spruce"]',54,36,36,'\\img\\products\\green-velvet-sofa.png','[]',NULL,0,1,'2020-12-22','ACME Furniture',0);
INSERT INTO "items" VALUES (23,'Grey Fabric Sofa','A large grey sofa for those with plenty of space.',83.99,5,'sofa','["Gray"]','["Fabric", "Wood"]','["Cloth", "Birch"]',78,36,36,'\\img\\products\\grey-fabric-sofa.png','[{"rating": 3, "content": "Not my Favorite, a bit wobbly", "userId": 9985}]',3.0,1,1,'2022-12-30','ACME Furniture',0);
INSERT INTO "items" VALUES (24,'Limestone Table With Base','A beige limestone table for dining.',119.99,0,'table','["Beige"]','["Stone"]','["Limestone"]',48,24,24,'\\img\\products\\limestone-table-with-base.png','[{"rating": 3, "content": "Not my Favorite, a bit wobbly", "userId": 9985}]',3.0,1,23,'2020-02-27','Homeware Inc.',0);
INSERT INTO "items" VALUES (25,'Limestone Two Legged Table','A beige limestone table for dining.',109.99,1,'table','["Beige"]','["Stone"]','["Limestone"]',48,24,20,'\\img\\products\\limestone-two-legged-table.png','[{"rating": 3, "content": "Not my Favorite, a bit wobbly", "userId": 9985}]',3.0,1,4,'2024-03-25','Homeware Inc.',0);
INSERT INTO "items" VALUES (26,'Mahogany Table','A fancy mahogany table.',49.99,3,'table','["Brown"]','["Wood"]','["Mahogany"]',48,24,20,'\\img\\products\\mahogany-table.png','[]',NULL,0,4,'2020-03-04','ACME Furniture',0);
INSERT INTO "items" VALUES (27,'Marble Table with Metal Legs','A marble dining room table with shiny metal legs.',129.99,12,'table','["White", "Black", "Shiny"]','["Metal"]','["Marble", "Steel"]',48,24,24,'\\img\\products\\marble-and-metal-legged-table.png','[]',NULL,0,4,'2020-12-03','Homeware Inc.',0);
INSERT INTO "items" VALUES (28,'Marble Table with Base','A nice marble table with a sleek base.',125.99,2,'table','["White", "Black", "Shiny"]','["Stone"]','["Marble"]',48,24,24,'\\img\\products\\marble-table-with-base.png','[]',NULL,0,23,'2020-12-01','Homeware Inc.',0);
INSERT INTO "items" VALUES (29,'Marble Two Legged Table','A nice marble table with two thick legs.',119.99,0,'table','["White", "Black", "Shiny"]','["Stone"]','["Marble"]',48,24,24,'\\img\\products\\marble-two-legged-table.png','[{"rating": 5, "content": "Works Great! NO Problems Had", "userId": 9999}, {"rating": 3, "content": "Not my Favorite, a bit wobbly", "userId": 9985}]',4.0,2,3,'2023-04-06','Homeware Inc.',0);
INSERT INTO "items" VALUES (30,'Metal Circular Table','A simple aluminum table with rough texture.',89.99,23,'table','["Shiny"]','["Metal"]','["Aluminum"]',36,36,18,'\\img\\products\\metal-circular-table.png','[{"rating": 5, "content": "Works Great! NO Problems Had", "userId": 9999}, {"rating": 3, "content": "Not my Favorite, a bit wobbly", "userId": 9985}]',4.0,2,9,'2023-11-12','ACME Furniture',0);
INSERT INTO "items" VALUES (31,'Naturalistic Acacia Wood Table','An acacia table with dark metal legs. Preserves natural beauty.',55.99,1,'table','["Brown", "Gray"]','["Wood", "Metal"]','["Acacia", "Steel"]',48,24,24,'\\img\\products\\naturalistic-acacia-wood-table.png','[]',NULL,0,3,'2022-11-22','ACME Furniture',0);
INSERT INTO "items" VALUES (32,'Oak Fancy Table','An oak table with a bit of extra flare.',29.99,3,'table','["Brown"]','["Wood"]','["Oak"]',48,24,24,'\\img\\products\\oak-fancy-table.png','[]',NULL,0,5,'2022-11-22','Homeware Inc.',0);
INSERT INTO "items" VALUES (33,'Oak Living Room Table','An oak table that is great for your living room.',27.99,5,'table','["Brown"]','["Wood"]','["Oak"]',48,24,24,'\\img\\products\\oak-living-room-table.png','[]',NULL,0,23,'2022-01-24','Homeware Inc.',0);
INSERT INTO "items" VALUES (34,'Quartz Table with Metal legs','An elegant quartz table with metal support.
For those who want a modern looking home.',107.99,2,'table','["White", "Black", "Shiny"]','["Stone", "Metal"]','["Quartz", "Steel"]',48,24,20,'\\img\\products\\quartz-with-metal-legs-table.png','[{"rating": 2, "content": "Eh, this isn''t good", "userId": 9901}, {"rating": 5, "content": "Works Great! NO Problems Had", "userId": 9999}]',3.5,2,6,'2022-01-24','Homeware Inc.',0);
INSERT INTO "items" VALUES (35,'Rectangular Wooden Chair','A simple rectangular wooden chair for those with minimalist tastes.',16.99,0,'chair','["Brown"]','["Wood"]','["Oak"]',12,12,22,'\\img\\products\\rectangular-wooden-chair.png','[]',NULL,0,9,'2020-04-21','ACME Furniture',0);
INSERT INTO "items" VALUES (36,'Red Fabric Bean Bag','A comfy red bean bag for relaxing.',23.99,4,'bean bag','["Red"]','["Fabric"]','["Leather"]',36,36,36,'\\img\\products\\red-fabric-bean-bag.png','[]',NULL,0,0,'2025-01-14','ACME Furniture',1);
INSERT INTO "items" VALUES (37,'Red Plastic Chair','A cheap red plastic chair. Good for parties and classrooms.',11.99,31,'chair','["Red"]','["Plastic"]','["Polyethylene"]',12,12,24,'\\img\\products\\red-plastic-chair.png','[]',NULL,0,13,'2020-10-16','ACME Furniture',0);
INSERT INTO "items" VALUES (38,'Red Twin Size Bed','A red metal twin sized bed for those who like colorful furniture.',68.99,6,'bed','["Red", "White"]','["Fabric", "Metal"]','["Velvet", "Cloth", "Steel"]',38,75,36,'\\img\\products\\red-twin-size-bed.png','[{"rating": 2, "content": "Eh, this isn''t good", "userId": 9901}]',2.0,1,18,'2020-01-16','ACME Furniture',1);
INSERT INTO "items" VALUES (39,'Red Wooden Desk','A red wooden desk for studying.',41.99,9,'desk','["Red"]','["Wood"]','["Spruce"]',48,24,24,'\\img\\products\\red-wooden-desk.png','[{"rating": 2, "content": "Eh, this isn''t good", "userId": 9901}, {"rating": 5, "content": "Works Great! NO Problems Had", "userId": 9999}]',3.5,2,20,'2019-04-17','Office Pal',1);
INSERT INTO "items" VALUES (40,'Sleek Wooden Chair','A sleek wooden chair with an unusual design.',18.99,1,'chair','["Brown"]','["Wood"]','["Oak"]',12,12,20,'\\img\\products\\sleek-wooden-chair.png','[{"rating": 5, "content": "Works Great! NO Problems Had", "userId": 9999}, {"rating": 3, "content": "Not my Favorite, a bit wobbly", "userId": 9985}]',4.0,2,9,'2019-05-03','ACME Furniture',0);
INSERT INTO "items" VALUES (41,'Spruce Wood Chair','A simple spruce chair for dining.',10.99,7,'chair','["Brown"]','["Wood"]','["Spruce"]',12,12,24,'\\img\\products\\spruce-wood-chair.png','[{"rating": 3, "content": "Not my Favorite, a bit wobbly", "userId": 9985}]',3.0,1,12,'2019-04-05','ACME Furniture',0);
INSERT INTO "items" VALUES (42,'Spruce Wood Table','A simple spruce table for dining.',39.99,14,'table','["Brown"]','["Wood"]','["Spruce"]',48,24,28,'\\img\\products\\spruce-wood-table.png','[{"rating": 4, "content": "Its decent", "userId": 9989}]',4.0,1,22,'2022-06-29','ACME Furniture',0);
INSERT INTO "items" VALUES (43,'Twin Sized Bed','A nice twin sized bed with a soft backdrop.',58.99,2,'bed','["Gray", "Brown", "White", "Beige", "Red"]','["Fabric", "Wood"]','["Cloth", "Oak"]',38,75,36,'\\img\\products\\twin-sized-bed.png','[{"rating": 4, "content": "Its decent", "userId": 9989}]',4.0,1,22,'2020-10-15','ACME Furniture',0);
INSERT INTO "items" VALUES (44,'White and Beige Queen Sized Bed','A nice queen sized bed with a soft backdrop.',108.99,3,'bed','["Gray", "Brown", "White", "Beige"]','["Fabric", "Wood"]','["Cloth", "Oak"]',60,80,48,'\\img\\products\\white-and-beige-queen-sized-bed.png','[]',NULL,0,0,'2020-06-30','ACME Furniture',0);
INSERT INTO "items" VALUES (45,'White and Brown King Sized Bed','A comfortable king sized bed with a large foam backdrop.',128.99,2,'bed','["White", "Gray"]','["Fabric", "Other", "Wood"]','["Cloth", "Foam", "Spruce"]',76,80,66,'\\img\\products\\white-and-brown-king-sized-bed.png','[{"rating": 2, "content": "Eh, this isn''t good", "userId": 9901}, {"rating": 5, "content": "Works Great! NO Problems Had", "userId": 9999}]',3.5,2,3,'2020-10-02','Homeware Inc.',0);
INSERT INTO "items" VALUES (46,'White Polypropylene Chair','A cheap plastic chair. Made from polypropylene.',15.99,29,'chair','["White"]','["Plastic"]','["Polypropylene"]',12,12,24,'\\img\\products\\white-polypropylene-chair.png','[{"rating": 2, "content": "Eh, this isn''t good", "userId": 9901}, {"rating": 5, "content": "Works Great! NO Problems Had", "userId": 9999}]',3.5,2,22,'2023-03-22','ACME Furniture',0);
INSERT INTO "items" VALUES (47,'White Wooden Desk','A white wooden desk for productivity.',45.99,8,'desk','["White"]','["Wood"]','["Oak"]',48,24,28,'\\img\\products\\white-wooden-desk.png','[{"rating": 4, "content": "Its decent", "userId": 9989}]',4.0,1,1,'2023-03-31','Office Pal',0);
INSERT INTO "items" VALUES (48,'White Wooden Nightstand','A white wooden nightstand for the bedroom.',24.99,12,'nightstand','["White"]','["Wood"]','["Oak"]',16,16,22,'\\img\\products\\white-wooden-nightstand.png','[{"rating": 2, "content": "Eh, this isn''t good", "userId": 9901}]',2.0,1,27,'2022-04-22','ACME Furniture',0);
INSERT INTO "items" VALUES (49,'Wooden Circular Table','A wooden circular table with some style.',39.99,15,'table','["Brown"]','["Wood"]','["Oak"]',36,36,20,'\\img\\products\\wooden-circular-table.png','[{"rating": 5, "content": "Works Great! NO Problems Had", "userId": 9999}, {"rating": 3, "content": "Not my Favorite, a bit wobbly", "userId": 9985}, {"rating": 4, "content": "Its decent", "userId": 9989}]',4.0,3,54,'2022-04-13','ACME Furniture',0);
INSERT INTO "items" VALUES (50,'Wooden Night Stand','A wooden night stand with a single drawer.',27.99,0,'nightstand','["Beige"]','["Wood"]','["Birch"]',16,16,24,'\\img\\products\\wooden-nightstand.png','[{"rating": 5, "content": "Works Great! NO Problems Had", "userId": 9999}, {"rating": 3, "content": "Not my Favorite, a bit wobbly", "userId": 9985}, {"rating": 4, "content": "Its decent", "userId": 9989}]',4.0,3,39,'2025-06-04','Homeware Inc.',0);
INSERT INTO "users" VALUES (1,'Markus M. Reever','mReever0707','revshark24@fakemail.com','4567','1999-05-29',0,1,'[]','[]','\public\img\user-icons\user-icon-1.png');
INSERT INTO "users" VALUES (2,'Aiza Omar','omar3a','omega3030@fakemail.com','3456ab','1994-02-05',0,1,'[]','[]','\public\img\user-icons\user-icon-2.png');
INSERT INTO "users" VALUES (3,'Mike Schultz','shu1tzM','mikeschul8899@fakemail.com','$Xyz','2001-11-30',0,1,'[]','[]','\public\img\user-icons\user-icon-3.png');
INSERT INTO "users" VALUES (4,'Abby Stewart','abb1010','stewab7@fakemail.com','kitten32','2004-03-15',0,1,'[]','[]','\public\img\user-icons\user-icon-4.png');
INSERT INTO "users" VALUES (5,'Mike Smith','msmith2','msmith2@fakemail.com','#1112!','2000-08-23',0,1,'[]','[]','\public\img\user-icons\user-icon-5.png');
INSERT INTO "users" VALUES (6,'Michelle B. Bloomberg','michelleB60','mbloomberg@fakemail.com','aXt1_yR','1979-10-14',0,1,'[]','[]','\public\img\user-icons\user-icon-6.png');
COMMIT;
